### ISSUE TITLE
FR: Add a /price command

### ISSUE THREAD

**Issue by EggPool** [Endogen/Telegram-Bauer-Bot#1]
To allow for easy tracking of price on the various exchanges.

Easy with CoinGecko API, see how pawer handles it:
https://github.com/bismuthfoundation/Pawer-discord-bot/blob/b66bb9477347f66119e9c4c13c6fea6be5dfa937/cogs/bismuth.py#L81

**Comment by Endogen** [comment]
I will add that. Thanks for the suggestion!

**Comment by Endogen** [comment]
See this [commit](https://github.com/Endogen/Telegram-Bauer-Bot/commit/9f8ca90320dab880398ab859948106cea7400208)

But you will have to add a new dependency
`pip3 install pycoingecko`
